server {
    listen 80;
    server_name hart4elkaar.nl www.hart4elkaar.nl;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    http2 on;
    server_name hart4elkaar.nl www.hart4elkaar.nl;

    ssl_certificate /etc/letsencrypt/live/hart4elkaar.nl/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/hart4elkaar.nl/privkey.pem;
    include /etc/nginx/conf.d/include/tls.conf;

    location / {
        resolver 127.0.0.11 valid=10s;
        set $upstream http://hartvoorelkaar-web:8080;
        proxy_pass $upstream;
        include /etc/nginx/conf.d/include/proxy.conf;
    }
}
